// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.laibao.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shengsiyuan.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.laibao.netty.proto.StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.shengsiyuan.proto.StudentResponse studentResponse = 1;</code>
   */
  com.laibao.netty.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.shengsiyuan.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.shengsiyuan.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.laibao.netty.proto.StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.shengsiyuan.proto.StudentResponse studentResponse = 1;</code>
   */
  com.laibao.netty.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
